### ISSUE TITLE
How to find Socket & Host Url

### ISSUE THREAD

**Issue by David2535418** [shivaya-dav/DogeRat#12]
Please tell me how to find socket and host url on glitch ? 
![68747470733a2f2f3939397870726f6669742e636f6d2f646f67732f31322e6a7067](https://user-images.githubusercontent.com/91040628/178469109-1ffc3b72-a4f6-433a-840b-2b7f95af60c3.jpeg)

**Comment by shivaya-dav** [comment]
After uploading files on GitHub open in new tab then , copy url

**Comment by shivaya-dav** [comment]
Check tutorial uploaded on telegram channel
