### ISSUE TITLE
Crashes!!!

### ISSUE THREAD

**Issue by Emmanho2** [shivaya-dav/DogeRat#15]
The new apks crashes even before installation. Please fix

**Comment by shivaya-dav** [comment]
Don't install apk first , download apk edit key.json file then install apk otherwise you will face crash issue, also you can change the apk resources editor , and don't sign the apk last one don't change pacakage name or etc

**Comment by gamerxdyt** [comment]
Sir please @shivaya-dav please my command how to use get storage command

**Comment by gamerxdyt** [comment]
@shivaya-dav , I write /storage/emulated/0/DCMI in reply but your tool saying no such file , please help how to write get folder command

**Comment by shivaya-dav** [comment]
dont write storage/emulated/0/ just type folder name you dont need to write root directory

**Comment by gamerxdyt** [comment]
@shivaya-dav but bro it's not work , when I click get folder and write , Telegram . I get response their is not such file
