### ISSUE TITLE
Apk Causes File Manager and Apk editor to Crash 

### ISSUE THREAD

**Issue by Emmanho2** [shivaya-dav/DogeRat#17]
> Don't install apk first , download apk edit key.json file then install apk otherwise you will face crash issue, also you can change the apk resources editor , and don't sign the apk last one don't change pacakage name or etc

The file does not  allow me to edit it. Once I open the folder where the apk is stored/downloaded, the file manager or apk editor app crashes.

**Comment by shivaya-dav** [comment]
Videos uploaded on telegram channel
