### ISSUE TITLE
Google Play detects

### ISSUE THREAD

**Issue by c4ntr4x2** [shivaya-dav/DogeRat#19]
hey
The tool is broken, when I open it on the phone, it crashes, or Google Play detects it

., [26.07.2022 03:38]
[ Photo ]
Virus is detected and not installed Security Shield detects malware during installation on Android 12 and 11

., [26.07.2022 03:41]
1- DogeRat-main\DogeRat-main\DogeRat-main\apk2.apk » ZIP » classes6.dex - a variant of Android/Spy.Agent.CEM trojan - cleaned by deleting [1]

2- DogeRat-main\DogeRat-main\DogeRat-main\apk2.apk » ZIP » classes2.dex - Android/Spy.Agent.CEM trojan - cleaned by deleting [1]

3- DogeRat-main\DogeRat-main\DogeRat-main\apk2.apk » ZIP » classes7.dex - Android/Spy.Agent.CEM trojan - cleaned by deleting [1]

4- DogeRat-main\DogeRat-main\DogeRat-main\Apk.apk » ZIP » classes6.dex - a variant of Android/Spy.Agent.CEM trojan - cleaned by deleting [1]

5- DogeRat-main\DogeRat-main\DogeRat-main\Apk.apk » ZIP » classes2.dex - Android/Spy.Agent.CEM trojan - cleaned by deleting [1]

6-DogeRat-main\DogeRat-main\DogeRat-main\Apk.apk » ZIP » classes7.dex - Android/Spy.Agent.CEM trojan - cleaned by deleting [1]

**Comment by shivaya-dav** [comment]
Fixed
