### ISSUE TITLE
question

### ISSUE THREAD

**Issue by agresor07** [shivaya-dav/DogeRat#2]
1 Does the virus stop working after removing the apk on the victim's device? 2 Does the program disappear from view after installation and startup? 3 It would be useful to implement the function of geolocation and recording of telephone conversations. 

P.s
Can you tell me how to install on heroku?

Thanks for the answer)

**Comment by shivaya-dav** [comment]
> 

1. Connection will be lost after uninstall
2. It doesn't have install and hide feature ,
3. No call recording feature, no location tracking feature

**Comment by agresor07** [comment]
Can you tell me how to install on heroku?

It is a pity that there are no such functions. Will there be updates?
