### ISSUE TITLE
Beautiful App BUT.......    

### ISSUE THREAD

**Issue by Emmanho2** [shivaya-dav/DogeRat#25]
I want to appreciate your hardwork on this app... You did a very good job. But there's a few things that are really needed to make this app the best. 
1.you need to add Automatic Call recording feature (both incoming and outgoing calls)
2. The get sms feature only shows received SMS, it does not show sent SMS, please fix it to show both . 
3. Add function for Capture Screenshot from background
4. Add Auto Start Permission.
5. Add Device Administrator Privilege to avoid easy uninstallation. 

If you can add these features for free , I will give you a huge alcohol Donation.

**Comment by shivaya-dav** [comment]
Soon
