### ISSUE TITLE
This guy called shiva is a scammer scammed me for 400$.

### ISSUE THREAD

**Issue by jrnassarr** [shivaya-dav/DogeRat#81]
![image](https://github.com/shivaya-dav/DogeRat/assets/110086147/cf4aeaaa-0cd8-47e9-a1af-5980af3f2722)
Scammer
Scammer
Don't deal with him scammed me for paid android rat.

**Comment by jemsvaib** [comment]
It's really unsatisfactory. But if it's from other but it should still work.

**Comment by jemsvaib** [comment]
Maybe need some fixing

**Comment by jemsvaib** [comment]
That's sure is scamming. I'm curious to go through that code cause i once thought about buying it.

**Comment by jemsvaib** [comment]
And one reason cause it's telegram bot controlled i can also make trough termux but it's interesting.

**Comment by jrnassarr** [comment]
Don't deal with him I swear to god he is a scammer 
And also the premium doge rat is shit. 
When I tried it and try to get photos from the phone it disconnected 
Bro text me on tele i have good rat. Ifound it after i got scammed from shiva. 
@thutmos

**Comment by jemsvaib** [comment]
Check your dm in telegram

**Comment by shivaya-dav** [comment]
After taking codes and everything the guy was asking for refund when I denied he was abused my country my god's, and me so blocked him, there is not my mistake this guy was a noob reverse engineer and he was thinking that he can steal my latest premium version but lol scammer got scammed,
